# https://wandb.ai

wandb:
  _target_: pytorch_lightning.loggers.wandb.WandbLogger
  entity: null  # optionally set to name of your wandb team
  name: ${name}
  tags: []
  notes: "..."
  project: "GCC22-Climate-ML-workshop"
  group: ""
  resume: "allow"
  reinit: True
  mode: online              # disabled  # disabled for no wandb logging
  save_dir: ${work_dir}/
  offline: False           # set True to store all logs only locally
  id: null                 # pass correct id to resume experiment!
  log_model: True         # True or 'all'
  prefix: ""
  job_type: "train"
  anonymous: 'allow'
