FROM pytorchlightning/pytorch_lightning:base-cuda-py3.9-torch1.12-cuda11.6.1
LABEL maintainer="Salva Ruhling Cachay <sruhlingcachay@ucsd.edu>"

# ----------------------------------------------------------------
# This image is available at:
# https://hub.docker.com/repository/docker/salv4/climateml
# ----------------------------------------------------------------

USER $NB_USER
ENV USER=${NB_USER}

RUN apt-get update \
    && apt-get install -yq --no-install-recommends vim emacs \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip install pytorch-lightning xarray netCDF4 dask einops hydra-core wandb
